# Generated by Django 3.2.4 on 2021-10-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='break_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='productive_time',
            field=models.IntegerField(default=0),
        ),
    ]
