# Generated by Django 3.2.4 on 2022-01-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0003_auto_20211022_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default_profile.svg', upload_to='static/profilepics/'),
        ),
    ]
